// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieAppMVC.DAL;

#nullable disable

namespace MovieAppMVC.Migrations
{
    [DbContext(typeof(MovieDBContext))]
    [Migration("20220911222551_MovieAndCategory")]
    partial class MovieAndCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieAppMVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Action"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Thriller"
                        });
                });

            modelBuilder.Entity("MovieAppMVC.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ReleasedYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Director = "Peter Jackson",
                            Duration = 180,
                            MovieName = "Lord Of The Rings I - The Fellowship of the Ring",
                            ReleasedYear = 2001
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            Director = "Joseph Kosinski",
                            Duration = 131,
                            MovieName = "Top Gun: Maverick",
                            ReleasedYear = 2022
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Director = "Adam McKay",
                            Duration = 145,
                            MovieName = "Don't Look Up",
                            ReleasedYear = 2021
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Director = "Julius Berg",
                            Duration = 92,
                            MovieName = "The Hunt",
                            ReleasedYear = 2020
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Director = "Chris Columbus",
                            Duration = 161,
                            MovieName = "Harry Potter and the Chamber of Secrets ",
                            ReleasedYear = 2002
                        });
                });

            modelBuilder.Entity("MovieAppMVC.Models.Movie", b =>
                {
                    b.HasOne("MovieAppMVC.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MovieAppMVC.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
